In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
ct = pd.read_csv('Company_Turnover.csv')
ct.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
features = ct.iloc[:,[0,1,2]]
features.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [8]:
labels = ct.iloc[:,-1]
labels.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,y_train,y_test = train_test_split(features , labels , test_size = 0.2 , random_state = 1)

In [50]:
X_train

R&D Spend  Administration  Marketing Spend
32   63408.86       129219.61         46085.25
39   38558.51        82982.09        174999.30
21   78389.47       153773.43        299737.29
36   28663.76       127056.21        201126.82
19   86419.70       153514.11             0.00
42   23640.93        96189.63        148001.11
49       0.00       116983.80         45173.06
26   75328.87       144135.98        134050.07
22   73994.56       122782.75        303319.26
13   91992.39       135495.07        252664.93
41   27892.92        84710.77        164470.71
17   94657.16       145077.58        282574.31
45    1000.23       124153.04          1903.93
24   77044.01        99281.34        140574.81
23   67532.53       105751.03        304768.73
4   142107.34        91391.77        366168.42
33   55493.95       103057.49        214634.81
14  119943.24       156547.42        256512.92
30   61994.48       115641.28         91131.24
10  101913.08       110594.11        229160.95
28   66051.52       182645.56        118148.20
44   22177.74       154806.14         28334.72
34   46426.07       157693.92        210797.67
18   91749.16       114175.79        294919.57
20   76253.86       113867.30        298664.47
25   64664.71       139553.16        137962.62
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
47       0.00       135426.92             0.00
1   162597.70       151377.59        443898.53
16   78013.11       121597.55        264346.06
0   165349.20       136897.80        471784.10
15  114523.61       122616.84        261776.23
5   131876.90        99814.71        362861.36
11  100671.96        91790.61        249744.55
9   123334.88       108679.17        304981.62
8   120542.52       148718.95        311613.29
12   93863.75       127320.38        249839.44
43   15505.73       127382.30         35534.17
37   44069.95        51283.14        197029.42

In [51]:
X_train = X_train.iloc[:,:].values
X_train

array([[ 63408.86, 129219.61,  46085.25],
       [ 38558.51,  82982.09, 174999.3 ],
       [ 78389.47, 153773.43, 299737.29],
       [ 28663.76, 127056.21, 201126.82],
       [ 86419.7 , 153514.11,      0.  ],
       [ 23640.93,  96189.63, 148001.11],
       [     0.  , 116983.8 ,  45173.06],
       [ 75328.87, 144135.98, 134050.07],
       [ 73994.56, 122782.75, 303319.26],
       [ 91992.39, 135495.07, 252664.93],
       [ 27892.92,  84710.77, 164470.71],
       [ 94657.16, 145077.58, 282574.31],
       [  1000.23, 124153.04,   1903.93],
       [ 77044.01,  99281.34, 140574.81],
       [ 67532.53, 105751.03, 304768.73],
       [142107.34,  91391.77, 366168.42],
       [ 55493.95, 103057.49, 214634.81],
       [119943.24, 156547.42, 256512.92],
       [ 61994.48, 115641.28,  91131.24],
       [101913.08, 110594.11, 229160.95],
       [ 66051.52, 182645.56, 118148.2 ],
       [ 22177.74, 154806.14,  28334.72],
       [ 46426.07, 157693.92, 210797.67],
       [ 91749.16, 114175.79, 2949

In [52]:
from sklearn import linear_model as lm
lr = lm.LinearRegression()

In [53]:
model = lr.fit(X_train , y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [54]:
print("Accuracy is :%.2f"%(model.score(X_train,y_train)*100))

Accuracy is :94.24


In [55]:
y_test_pred = model.predict(X_test)
y_test_pred

array([114729.00768236,  90569.03231312,  75952.34861633,  70179.81117586,
       179539.15187896, 171638.15637459,  49624.94193162, 102253.12475568,
        58381.67907   ,  98240.74724733])

In [56]:
y_test

27    105008.31
35     96479.51
40     78239.91
38     81229.06
2     191050.39
3     182901.99
48     35673.41
29    101004.64
46     49490.75
31     97483.56
Name: Profit, dtype: float64

In [57]:
y_train_pred = model.predict(X_train)
y_train_pred

array([ 98969.52756204,  83919.3956522 , 117796.58522119,  76639.06958456,
       115218.91821656,  71461.95155152,  49958.79852998, 110648.85775917,
       114771.00173102, 127106.80565231,  75337.90528303, 129963.63026184,
        49400.39090935, 112561.66577897, 109960.01968065, 169623.97770364,
        98018.01735043, 148674.68879281,  99315.66642717, 134316.03256903,
       102661.81733079,  66302.90500978,  90405.77692849, 128345.62925698,
       116461.74705113, 102547.66847856, 156335.93159848, 158765.16200826,
        48471.24187251, 187242.78207997, 116748.74740429, 190318.42240258,
       144930.8979623 , 161532.60591262, 134124.19842044, 153142.89097745,
       150824.4573188 , 128544.39722339,  61589.2675441 ,  89110.9770016 ])

In [58]:
y_train

32     97427.84
39     81005.76
21    111313.02
36     90708.19
19    122776.86
42     71498.49
49     14681.40
26    105733.54
22    110352.25
13    134307.35
41     77798.83
17    125370.37
45     64926.08
24    108552.04
23    108733.99
4     166187.94
33     96778.92
14    132602.65
30     99937.59
10    146121.95
28    103282.38
44     65200.33
34     96712.80
18    124266.90
20    118474.03
25    107404.34
6     156122.51
7     155752.60
47     42559.73
1     191792.06
16    126992.93
0     192261.83
15    129917.04
5     156991.12
11    144259.40
9     149759.96
8     152211.77
12    141585.52
43     69758.98
37     89949.14
Name: Profit, dtype: float64

In [59]:
print("\nSlope is:",(model.coef_))
print("\n Intercept is",(model.intercept_))


Slope is: [ 0.7742023  -0.00877164  0.02934891]

 Intercept is 49659.157733186345


In [60]:
from sklearn.metrics import mean_squared_error,r2_score

In [61]:
print("The RMSE and R-Squared values of the train data is:")
print("\n")
rmse_train = np.sqrt(mean_squared_error(y_train,y_train_pred))
r2_train = r2_score(y_train,y_train_pred)
print("RMSE value is :",rmse_train)
print("R-Square Value is:%.2f"%(r2_train))

The RMSE and R-Squared values of the train data is:


RMSE value is : 8949.832282183112
R-Square Value is:0.94


In [63]:
print("\n The RMSE and R-Squared value of the test data is :")
print("\n")
rmse_test = np.sqrt(mean_squared_error(y_test , y_test_pred))
r2_test = r2_score(y_test , y_test_pred)
print("RMS for test data is : " , rmse_test)
print("R-Square value for test data is :%.2f"%(r2_test))


 The RMSE and R-Squared value of the test data is :


RMS for test data is :  8899.174159891012
R-Square value for test data is :0.97
